spring:
  application:
    name: zuul-proxy
zuul:
  routes:
    api-provider:
      path: /provider/**
      serviceId: eureka-provider

eureka:
  server:
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/