spring:
  application:
    name: eureka-remote
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/